//! Privacy-aware clipboard sensor (via the Swift helper).
//!
//! `clipboard_peek` reads only the pasteboard `changeCount` (no content, so it
//! does not trigger the macOS "paste from other app" alert). `clipboard_read`
//! returns text only when no concealed / transient / auto-generated marker is
//! present. The host re-checks the reported type identifiers (defense in depth),
//! so text is dropped even if a helper bug returned it alongside a marker.
// Parts are only reached from macOS-only code paths; the rest is tested everywhere.
#![cfg_attr(not(target_os = "macos"), allow(dead_code))]

use super::types::SensorError;

const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
];
const TRANSIENT_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "de.petermaurer.TransientPasteboardType",
];
const AUTO_GENERATED_TYPES: &[&str] = &["org.nspasteboard.AutoGeneratedType"];

/// Pasteboard type identifiers set by password managers and by apps that mark
/// the content as secret or short-lived. Any of these means: do not read.
/// (Mirrors the Swift helper's list; kept in sync by `clipboard_tests`.)
pub const SENSITIVE_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClipboardPeek {
    pub change_count: i64,
    /// macOS 15.4+ pasteboard privacy setting (`ask`, `always_allow`, ...), if known.
    pub access_behavior: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClipboardRead {
    pub change_count: i64,
    pub concealed: bool,
    pub transient: bool,
    pub auto_generated: bool,
    pub has_text: bool,
    /// Present only for non-sensitive plain text, capped to the requested length.
    pub text: Option<String>,
    pub truncated: bool,
}

impl ClipboardRead {
    /// True when the pasteboard is marked secret/short-lived.
    pub fn is_sensitive(&self) -> bool {
        self.concealed || self.transient || self.auto_generated
    }
}

pub(super) fn parse_peek(v: &serde_json::Value) -> Result<ClipboardPeek, SensorError> {
    let change_count = v
        .get("change_count")
        .and_then(|c| c.as_i64())
        .ok_or_else(|| SensorError::Failed("clipboard_peek: missing change_count".into()))?;
    Ok(ClipboardPeek {
        change_count,
        access_behavior: v
            .get("access_behavior")
            .and_then(|a| a.as_str())
            .map(str::to_string),
    })
}

pub(super) fn parse_read(
    v: &serde_json::Value,
    max_chars: usize,
) -> Result<ClipboardRead, SensorError> {
    let change_count = v
        .get("change_count")
        .and_then(|c| c.as_i64())
        .ok_or_else(|| SensorError::Failed("clipboard_read: missing change_count".into()))?;
    let flag = |k: &str| v.get(k).and_then(|b| b.as_bool()).unwrap_or(false);
    let types: Vec<&str> = v
        .get("types")
        .and_then(|t| t.as_array())
        .map(|ts| ts.iter().filter_map(|t| t.as_str()).collect())
        .unwrap_or_default();
    let has_type = |set: &[&str]| types.iter().any(|t| set.contains(t));
    let concealed = flag("concealed") || has_type(CONCEALED_TYPES);
    let transient = flag("transient") || has_type(TRANSIENT_TYPES);
    let auto_generated = flag("auto_generated") || has_type(AUTO_GENERATED_TYPES);
    let sensitive = concealed || transient || auto_generated;
    let mut text = None;
    let mut truncated = flag("truncated");
    if !sensitive {
        if let Some(t) = v.get("text").and_then(|t| t.as_str()) {
            if t.chars().count() > max_chars {
                truncated = true;
            }
            text = Some(t.chars().take(max_chars).collect::<String>());
        }
    }
    Ok(ClipboardRead {
        change_count,
        concealed,
        transient,
        auto_generated,
        has_text: flag("has_text") || text.is_some(),
        text,
        truncated,
    })
}

/// Cheap clipboard change probe (`changeCount` only).
#[cfg(target_os = "macos")]
pub fn clipboard_peek() -> Result<ClipboardPeek, SensorError> {
    let resp = super::sensor_util::call_helper(
        &serde_json::json!({"type": "clipboard_peek"}),
        super::sensor_util::SENSOR_TIMEOUT,
    )?;
    parse_peek(&resp)
}

/// Read the clipboard text, honouring concealed/transient markers. Never logs content.
#[cfg(target_os = "macos")]
pub fn clipboard_read(max_chars: usize) -> Result<ClipboardRead, SensorError> {
    let resp = super::sensor_util::call_helper(
        &serde_json::json!({"type": "clipboard_read", "max_chars": max_chars}),
        super::sensor_util::SENSOR_TIMEOUT,
    )?;
    let read = parse_read(&resp, max_chars)?;
    log::debug!(
        "[accessibility][sensors] clipboard_read change_count={} sensitive={} text_chars={}",
        read.change_count,
        read.is_sensitive(),
        read.text.as_ref().map(|t| t.chars().count()).unwrap_or(0)
    );
    Ok(read)
}

#[cfg(not(target_os = "macos"))]
pub fn clipboard_peek() -> Result<ClipboardPeek, SensorError> {
    Err(SensorError::Unsupported)
}

#[cfg(not(target_os = "macos"))]
pub fn clipboard_read(_max_chars: usize) -> Result<ClipboardRead, SensorError> {
    Err(SensorError::Unsupported)
}

#[cfg(test)]
#[path = "clipboard_tests.rs"]
mod tests;
