//! Swift source for the Pet Mode sensor commands of the unified helper:
//! `clipboard_peek`, `clipboard_read`, `frontmost_window`, `frame_signature`, `ocr`.
//!
//! Spliced into the helper source at the `// @@SENSORS_SWIFT@@` marker in
//! `helper.rs`. Everything between the BEGIN/END markers is covered by a string
//! test: it must never read `kAXValueAttribute` and never set
//! `AXEnhancedUserInterface` / `AXManualAccessibility`.
// Parts are only reached from macOS-only code paths; the rest is tested everywhere.
#![cfg_attr(not(target_os = "macos"), allow(dead_code))]

pub(super) const SENSORS_BEGIN: &str = "// SENSORS-BEGIN";
pub(super) const SENSORS_END: &str = "// SENSORS-END";

pub(super) const SENSORS_SWIFT: &str = r##"// SENSORS-BEGIN
import Vision
import ImageIO

// MARK: - Clipboard (changeCount peek + concealed-aware read)

let concealedPasteboardTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb",
]

func pasteboardAccessBehavior() -> Any {
    if #available(macOS 15.4, *) {
        switch NSPasteboard.general.accessBehavior {
        case .default: return "default"
        case .alwaysAllow: return "always_allow"
        case .alwaysDeny: return "always_deny"
        case .ask: return "ask"
        @unknown default: return "unknown"
        }
    }
    return NSNull()
}

/// changeCount only: never touches pasteboard contents.
func clipboardPeek(id: String?) -> [String: Any] {
    var r: [String: Any] = [
        "type": "clipboard_peek",
        "change_count": NSPasteboard.general.changeCount,
        "access_behavior": pasteboardAccessBehavior(),
        "error": NSNull(),
    ]
    if let id = id { r["id"] = id }
    return r
}

/// Reads plain text unless a concealed/transient/auto-generated marker is present.
/// `types` lists type identifiers only (never content) so the host can double-check.
func clipboardRead(id: String?, maxChars: Int) -> [String: Any] {
    let pb = NSPasteboard.general
    let count = pb.changeCount
    let typeNames = (pb.types ?? []).map { $0.rawValue }
    let concealed = typeNames.contains("org.nspasteboard.ConcealedType")
        || typeNames.contains("com.agilebits.onepassword")
        || typeNames.contains("net.antelle.keeweb")
    let transient = typeNames.contains("org.nspasteboard.TransientType")
        || typeNames.contains("de.petermaurer.TransientPasteboardType")
    let autoGenerated = typeNames.contains("org.nspasteboard.AutoGeneratedType")
    var r: [String: Any] = [
        "type": "clipboard_read",
        "change_count": count,
        "concealed": concealed,
        "transient": transient,
        "auto_generated": autoGenerated,
        "types": typeNames,
        "has_text": typeNames.contains("public.utf8-plain-text") || typeNames.contains("NSStringPboardType"),
        "error": NSNull(),
    ]
    if let id = id { r["id"] = id }
    if concealed || transient || autoGenerated { return r }
    if let s = pb.string(forType: .string) {
        let capped = String(s.prefix(max(0, maxChars)))
        r["text"] = capped
        r["truncated"] = capped.count < s.count
    }
    return r
}

// MARK: - Frontmost window id (for non-interactive window capture)

/// Topmost normal on-screen window of the frontmost application. Reads no window
/// names (those need Screen Recording); only ids, owner pid and size.
func frontmostWindow(id: String?) -> [String: Any] {
    var r: [String: Any] = ["type": "frontmost_window", "error": NSNull()]
    if let id = id { r["id"] = id }
    guard let front = NSWorkspace.shared.frontmostApplication else {
        r["error"] = "no_frontmost_app"
        return r
    }
    let pid = front.processIdentifier
    r["pid"] = Int(pid)
    let opts: CGWindowListOption = [.optionOnScreenOnly, .excludeDesktopElements]
    guard let list = CGWindowListCopyWindowInfo(opts, kCGNullWindowID) as? [[String: Any]] else {
        r["error"] = "window_list_unavailable"
        return r
    }
    for w in list {
        guard let owner = w[kCGWindowOwnerPID as String] as? Int, owner == Int(pid),
              let layer = w[kCGWindowLayer as String] as? Int, layer == 0,
              let num = w[kCGWindowNumber as String] as? Int else { continue }
        let alpha = (w[kCGWindowAlpha as String] as? Double) ?? 1.0
        var width = 0.0, height = 0.0
        if let b = w[kCGWindowBounds as String] as? [String: Any] {
            width = (b["Width"] as? Double) ?? 0
            height = (b["Height"] as? Double) ?? 0
        }
        if alpha <= 0.01 || width < 50 || height < 50 { continue }
        r["window_id"] = num
        r["w"] = Int(width)
        r["h"] = Int(height)
        return r
    }
    r["error"] = "no_capturable_window"
    return r
}

// MARK: - Image helpers: signature (change detection) and OCR

func loadCGImage(_ path: String) -> CGImage? {
    let url = URL(fileURLWithPath: path) as CFURL
    guard let src = CGImageSourceCreateWithURL(url, nil),
          CGImageSourceGetCount(src) > 0 else { return nil }
    return CGImageSourceCreateImageAtIndex(src, 0, nil)
}

func grayBitmap(_ image: CGImage, cols: Int, rows: Int) -> [UInt8]? {
    var buf = [UInt8](repeating: 0, count: cols * rows)
    let cs = CGColorSpaceCreateDeviceGray()
    let ok: Bool = buf.withUnsafeMutableBytes { raw in
        guard let ctx = CGContext(data: raw.baseAddress, width: cols, height: rows,
                                  bitsPerComponent: 8, bytesPerRow: cols, space: cs,
                                  bitmapInfo: CGImageAlphaInfo.none.rawValue) else { return false }
        ctx.interpolationQuality = .high
        ctx.draw(image, in: CGRect(x: 0, y: 0, width: cols, height: rows))
        return true
    }
    return ok ? buf : nil
}

/// Downscaled grayscale signature: render to 4x the grid, then box-average. Hex encoded.
func frameSignature(id: String?, path: String, cols: Int, rows: Int) -> [String: Any] {
    var r: [String: Any] = ["type": "frame_signature", "error": NSNull(), "cols": cols, "rows": rows]
    if let id = id { r["id"] = id }
    guard cols > 0, rows > 0, cols <= 256, rows <= 256 else { r["error"] = "bad_grid"; return r }
    guard let img = loadCGImage(path) else { r["error"] = "image_unreadable"; return r }
    let f = 4
    guard let big = grayBitmap(img, cols: cols * f, rows: rows * f) else { r["error"] = "bitmap_failed"; return r }
    var out = [UInt8](repeating: 0, count: cols * rows)
    for y in 0..<rows {
        for x in 0..<cols {
            var sum = 0
            for dy in 0..<f { for dx in 0..<f { sum += Int(big[(y * f + dy) * (cols * f) + (x * f + dx)]) } }
            out[y * cols + x] = UInt8(sum / (f * f))
        }
    }
    let hexDigits = Array("0123456789abcdef")
    var hex = ""
    hex.reserveCapacity(out.count * 2)
    for b in out { hex.append(hexDigits[Int(b >> 4)]); hex.append(hexDigits[Int(b & 0x0f)]) }
    r["signature"] = hex
    return r
}

/// On-device text recognition (Vision). The image never leaves this process.
func ocrImage(id: String?, path: String, maxChars: Int, accurate: Bool, maxDim: Int, languages: [String]) -> [String: Any] {
    let started = DispatchTime.now()
    var r: [String: Any] = ["type": "ocr", "error": NSNull(), "text": "", "lines": 0, "truncated": false]
    if let id = id { r["id"] = id }
    guard var img = loadCGImage(path) else { r["error"] = "image_unreadable"; return r }
    // Retina frames are 3000+ px wide; Vision cost scales with pixels, so cap the long edge.
    let longEdge = max(img.width, img.height)
    if maxDim > 0, longEdge > maxDim {
        let scale = Double(maxDim) / Double(longEdge)
        let w = max(1, Int(Double(img.width) * scale)), h = max(1, Int(Double(img.height) * scale))
        if let ctx = CGContext(data: nil, width: w, height: h, bitsPerComponent: 8, bytesPerRow: 0,
                               space: CGColorSpaceCreateDeviceGray(), bitmapInfo: CGImageAlphaInfo.none.rawValue) {
            ctx.interpolationQuality = .high
            ctx.draw(img, in: CGRect(x: 0, y: 0, width: w, height: h))
            if let small = ctx.makeImage() { img = small }
        }
    }
    let req = VNRecognizeTextRequest()
    req.recognitionLevel = accurate ? .accurate : .fast
    req.usesLanguageCorrection = accurate
    // Explicit languages only: automaticallyDetectsLanguage measured at ~19 s on a full
    // Retina frame (versus ~0.2 s with an explicit list), which is unusable for a sampler.
    req.automaticallyDetectsLanguage = false
    req.recognitionLanguages = languages.isEmpty ? ["en-US"] : languages
    let handler = VNImageRequestHandler(cgImage: img, options: [:])
    do { try handler.perform([req]) } catch {
        r["error"] = "vision_failed"
        return r
    }
    let obs = (req.results ?? []).sorted { a, b in
        let ay = a.boundingBox.maxY, by = b.boundingBox.maxY
        if abs(ay - by) > 0.008 { return ay > by }
        return a.boundingBox.minX < b.boundingBox.minX
    }
    var lines: [String] = []
    for o in obs {
        if let c = o.topCandidates(1).first, c.confidence >= 0.3, !c.string.isEmpty { lines.append(c.string) }
    }
    let joined = lines.joined(separator: "\n")
    let capped = String(joined.prefix(max(0, maxChars)))
    r["text"] = capped
    r["lines"] = lines.count
    r["truncated"] = capped.count < joined.count
    r["ms"] = Int((DispatchTime.now().uptimeNanoseconds - started.uptimeNanoseconds) / 1_000_000)
    return r
}
// SENSORS-END
"##;

#[cfg(test)]
mod tests {
    use super::*;

    fn region() -> &'static str {
        let a = SENSORS_SWIFT.find(SENSORS_BEGIN).expect("begin marker");
        let b = SENSORS_SWIFT.find(SENSORS_END).expect("end marker");
        &SENSORS_SWIFT[a..b]
    }

    #[test]
    fn sensor_swift_never_reads_ax_value_or_flips_ax_modes() {
        let r = region();
        for banned in [
            "kAXValueAttribute",
            "\"AXValue\"",
            "AXEnhancedUserInterface",
            "AXManualAccessibility",
            "AXUIElementSetAttributeValue",
            "AXUIElementCopyAttributeValue",
        ] {
            assert!(!r.contains(banned), "sensor swift must not use {banned}");
        }
    }

    #[test]
    fn sensor_swift_handles_concealed_types_and_has_all_commands() {
        let r = region();
        assert!(r.contains("org.nspasteboard.ConcealedType"));
        assert!(r.contains("org.nspasteboard.TransientType"));
        assert!(r.contains("org.nspasteboard.AutoGeneratedType"));
        assert!(r.contains("com.agilebits.onepassword"));
        for f in [
            "func clipboardPeek",
            "func clipboardRead",
            "func frontmostWindow",
            "func frameSignature",
            "func ocrImage",
        ] {
            assert!(r.contains(f), "{f}");
        }
        // OCR must stay on-device and language-explicit (auto-detect was ~19 s).
        assert!(r.contains("automaticallyDetectsLanguage = false"));
    }

    #[test]
    fn sensor_commands_are_dispatched_by_the_helper() {
        let helper = include_str!("helper.rs");
        for c in [
            "\"clipboard_peek\"",
            "\"clipboard_read\"",
            "\"frontmost_window\"",
            "\"frame_signature\"",
            "\"ocr\"",
        ] {
            assert!(helper.contains(&format!("case {c}:")), "{c}");
        }
        assert!(helper.contains("// @@SENSORS_SWIFT@@"));
    }

    #[test]
    fn clipboard_type_lists_match_the_swift_helper() {
        for ty in super::super::clipboard::SENSITIVE_PASTEBOARD_TYPES {
            assert!(region().contains(ty), "swift helper missing {ty}");
        }
    }
}
