use super::*;

#[test]
fn generated_paths_are_recognised() {
    assert!(is_generated_path("target/debug/x.rs"));
    assert!(is_generated_path("app/node_modules/a/b.js"));
    assert!(is_generated_path("Cargo.lock"));
    assert!(is_generated_path("web/app.min.js"));
    assert!(is_generated_path("a/b.map"));
    assert!(is_generated_path("tests/x.snap"));
    assert!(!is_generated_path("src/target.rs"));
    assert!(!is_generated_path("src/build.rs"));
    assert!(!is_generated_path("src/lib.rs"));
}

#[test]
fn a_generated_marker_near_the_top_counts_but_one_deep_in_the_file_does_not() {
    assert!(is_generated("a.rs", b"// @generated by tool\nfn a() {}\n"));
    assert!(is_generated("a.ts", b"/* DO NOT EDIT */\n"));
    assert!(is_generated("a.md", b"x\n<!-- BEGIN GENERATED: t -->\n"));
    let deep = format!("{}// @generated\n", "x\n".repeat(10));
    assert!(!is_generated("a.rs", deep.as_bytes()));
}

#[test]
fn binary_detection_uses_extension_and_nul() {
    assert!(looks_binary("a.png", b"text"));
    assert!(looks_binary("a.dat", b"ab\0cd"));
    assert!(!looks_binary("a.rs", b"fn main() {}"));
}

#[test]
fn exclude_globs_match_nested_vendor_trees_only() {
    let set = ExcludeSet::new(&["vendor/*/vendor/**".to_string()]);
    assert!(set.matches("vendor/a/vendor/b/c.rs"));
    assert!(set.matches("vendor/a/vendor/c.rs"));
    assert!(!set.matches("vendor/a/src/c.rs"));
    assert!(!set.matches("src/vendor/x.rs"));
    let bad = ExcludeSet::new(&["[".to_string()]);
    assert!(!bad.matches("anything"));
}

#[test]
fn the_walk_fallback_skips_build_dirs_and_lists_regular_files() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("target/debug")).unwrap();
    std::fs::create_dir_all(root.join("node_modules/p")).unwrap();
    std::fs::write(root.join("src/a.rs"), "fn a() {}").unwrap();
    std::fs::write(root.join("target/debug/b.rs"), "x").unwrap();
    std::fs::write(root.join("node_modules/p/i.js"), "x").unwrap();
    let listed = list_candidates(root).unwrap();
    assert_eq!(listed, vec!["src/a.rs".to_string()]);
}
