#!/usr/bin/env node
/**
 * Vendor the app's webfonts into `public/fonts/` and generate
 * `src/styles/fonts.css` from the result.
 *
 * WHY THIS EXISTS: `index.css` used to `@import` Inter and JetBrains Mono from
 * fonts.googleapis.com. OpenHuman is an offline-capable desktop app, so on a
 * cold start without a network the CSS import fails and the entire UI renders
 * in a system fallback face — a first-run regression nobody sees in dev,
 * because dev machines are online and the font is already cached.
 *
 * Re-run after changing weights or families:
 *   node scripts/fetch-fonts.mjs
 *
 * It is deliberately a checked-in generator rather than a build step: fetching
 * from a third party during every build would put a network dependency back
 * into the thing this removes.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

// A modern desktop UA, so Google serves woff2 rather than legacy formats.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { family: 'Inter', slug: 'inter', weights: [300, 400, 500, 600, 700] },
  { family: 'JetBrains Mono', slug: 'jetbrains-mono', weights: [300, 400, 500, 600] },
];

const FONT_DIR = new URL('../public/fonts/', import.meta.url);
const OUT_CSS = new URL('../src/styles/fonts.css', import.meta.url);

/** Parses `/* subset *\/ @font-face { ... }` pairs out of Google's CSS. */
function parseFaces(css, family) {
  const faces = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gi;
  let match;
  while ((match = re.exec(css)) !== null) {
    const [, subset, body] = match;
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const url = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!weight || !url || !unicodeRange) continue;
    faces.push({ family, subset, weight: Number(weight), url, unicodeRange: unicodeRange.trim() });
  }
  return faces;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  for (const existing of await readdir(FONT_DIR).catch(() => [])) {
    if (existing.endsWith('.woff2')) await rm(new URL(existing, FONT_DIR));
  }

  const chunks = [
    `/*\n * GENERATED by scripts/fetch-fonts.mjs - do not edit by hand.\n *\n * Self-hosted so the desktop app renders its real typefaces offline.\n *\n * ONE FILE PER SUBSET, NOT PER WEIGHT: both families are variable fonts on\n * Google Fonts, so every weight of a given subset resolves to the identical\n * woff2. Emitting one @font-face per weight downloaded the same bytes five\n * times (59 files, 13 unique payloads). Each rule below therefore declares a\n * font-weight RANGE and the browser interpolates.\n *\n * unicode-range is preserved from Google's own CSS, so a Latin-only session\n * still loads only the Latin subset.\n */\n`,
  ];

  for (const { family, slug, weights } of FAMILIES) {
    const href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, '+')}:wght@${weights.join(';')}&display=swap`;
    const res = await fetch(href, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${family}: ${res.status} ${res.statusText}`);
    const css = await res.text();

    const faces = parseFaces(css, family);
    if (faces.length === 0) throw new Error(`${family}: parsed no @font-face blocks`);

    // Collapse to one entry per subset, asserting the payload really is shared.
    const bySubset = new Map();
    for (const face of faces) {
      const entry = bySubset.get(face.subset);
      if (!entry) {
        bySubset.set(face.subset, { ...face, urls: new Set([face.url]) });
        continue;
      }
      entry.urls.add(face.url);
      entry.weight = Math.max(entry.weight, face.weight);
    }

    const minWeight = Math.min(...weights);
    const maxWeight = Math.max(...weights);

    for (const [subset, entry] of bySubset) {
      if (entry.urls.size !== 1) {
        // Not a variable font for this subset - fall back to per-weight files
        // rather than silently dropping weights.
        throw new Error(
          `${family}/${subset}: ${entry.urls.size} distinct payloads; this generator assumes a variable font`
        );
      }
      const [url] = entry.urls;
      const filename = `${slug}-${subset}.woff2`;
      const fontRes = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!fontRes.ok) throw new Error(`${filename}: ${fontRes.status}`);
      await writeFile(new URL(filename, FONT_DIR), Buffer.from(await fontRes.arrayBuffer()));

      chunks.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${minWeight} ${maxWeight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${filename}') format('woff2');\n` +
          `  unicode-range: ${entry.unicodeRange};\n` +
          `}\n`
      );
    }
    console.log(`${family}: ${bySubset.size} subsets (from ${faces.length} weight-subset pairs)`);
  }

  await writeFile(OUT_CSS, chunks.join('\n'));
  console.log(`wrote ${join('src', 'styles', 'fonts.css')}`);
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
